name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Versión de Python que deseas usar

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements.txt found, skipping."

      # Paso 4: Ejecutar pruebas unitarias
      - name: Run tests
        run: python -m unittest discover


