name: Python Application CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker con imagen de Python
      - name: Setup Docker with Python
        run: |
          docker pull python:3.9
          docker run --name python-container -d -v $(pwd):/app -w /app python:3.9 tail -f /dev/null

      # Paso 3: Instalar dependencias dentro del contenedor Docker
      - name: Install requirements
        run: |
          docker exec python-container pip install -r requirements.txt || echo "No requirements.txt found, skipping."

      # Paso 4: Analizar el código con pylint
      - name: Run Pylint
        run: |
          docker exec python-container pip install pylint
          docker exec python-container pylint *.py || echo "Pylint completed with warnings."

      # Paso 5: Ejecutar pruebas unitarias y coverage
      - name: Run tests and coverage
        run: |
          docker exec python-container pip install coverage
          docker exec python-container coverage run -m unittest discover
          docker exec python-container coverage report

	
